const STATUS_OK = 200;
const STATUS_CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const CONFLICT = 409;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
export default {
	STATUS_CREATED,
	STATUS_OK,
	BAD_REQUEST,
	UNAUTHORIZED,
	CONFLICT,
	NOT_FOUND,
	FORBIDDEN,
	SERVER_ERROR
};
